# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-graphql
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/**/*

Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false
GraphQL/ObjectDescription:
  Enabled: false

RSpec/ExampleLength:
  Max: 40
RSpec/MultipleExpectations:
  Enabled: false
RSpec/FilePath:
  Enabled: false
